config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "memos#index"
  resources :memos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :memos, dependent: :destroy
  validates :name, presence: true, uniqueness: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :name ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

  # index show以外はログイン画面のページをスキップできる
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  def index
    @memos = Memo.includes(:user).order(:id)
  end

  def new
    @memo = Memo.new
  end

  def create
    # DayOneの9/17にcreateじゃなくてsaveの理由を記載
    @memo = current_user.memos.new(memo_params)
    if @memo.save
      redirect_to root_path, notice: "投稿しました"
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :new
    end
  end

  def show
    @memo = Memo.find(params[:id])
  end

  def edit
  end

  def update
    if @memo.update(memo_params)
      redirect_to memo_path(@memo), notice: "更新しました"
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :edit
    end
  end

  def destroy
    @memo.destroy!
    redirect_to memos_path, alert: "削除しました"
  end

  private
  def memo_params
    params.require(:memo).permit(:title, :content, :image)
  end

  def correct_user
    @memo = current_user.memos.find_by(id: params[:id])
    redirect_to root_path if @memo.nil?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if @memo.errors.any? %>
  <div>
    <ul>
      <% @memo.errors.full_messages.each do |msg| %>
        <li><span style="color: red;"><%= msg %></span></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <p style="color: <%= flash_type == 'notice' ? 'green' : 'red' %>;"><%= msg %></p>
  <hr>
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  <%= link_to "投稿一覧", memos_path %>
  <%= link_to "新規投稿", new_memo_path %>
<% else %>
  <%= link_to "ログイン", new_user_session_path %>
  <%= link_to "新規登録", new_user_registration_path %>
  <%= link_to "投稿一覧", memos_path %>
<% end %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/header' %>
    <%= render '/layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/memos/_form.html.erb
<%= render "layouts/error_messages" %>
<%= form_with model: @memo, local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content, size: "45*30" %>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

    <%= form.submit button_value %>
<% end %>

app/views/memos/_memo.html.erb
  <p>
  投稿者：<%= memo.user.name %>
  タイトル：<%= memo.title %>
  <% if memo.image? %>
  <%= image_tag memo.image.thumb.url %>
  <% end %>
  </p>
    <%= link_to "詳細", memo_path(memo) %>  
    <% if user_signed_in? && current_user.id == memo.user.id %>
      <%= link_to "編集", edit_memo_path(memo) %>
      <%= link_to "削除", memo_path(memo), method: :delete, data: {confirm: "削除しますか？" } %>
      <% end %>
  </p>

app/views/memos/edit.html.erb
<h1>投稿編集</h1>
<%= render "form", button_value: "更新" %>

app/views/memos/index.html.erb
<h1>投稿一覧</h1>
<%= render @memos %>

app/views/memos/new.html.erb
<h1>新規投稿</h1>
<%= render "form", button_value: "投稿" %>

app/views/memos/show.html.erb
<h1>投稿詳細</h1>
<div class = memo_title><%= @memo.title %></div>
<div class = memo_content><%= simple_format(h @memo.content) %></div>

<%#= simple_format(h @post.content) %>

<% if @memo.image? %>
  <p><%= image_tag @memo.image.url, :size => '600*600' %></p>
<% end %>

<% if user_signed_in? && current_user.id == @memo.user.id %>
  <%= link_to "編集", edit_memo_path(@memo) %>
  <%= link_to "削除", memo_path(@memo), method: :delete, data: {confirm: "削除しますか？" } %>
<% end %>